spring:
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.stock: debug
  file: logs/${spring.application.name}.log
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    security:
      path: /api-s/**
      serviceId: security-center
    user:
      path: /api-u/**
      serviceId: user-center
  host:
    connect-timeout-millis: 10000001
    socket-timeout-millis: 60000001
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
security:
  oauth2:
    client:
      access-token-uri: http://gateway-center:8992/api-s/oauth/token
      user-authorization-uri: http://gateway-center:8992/api-s/security/v1/oauth/authorize
    resource:
      user-info-uri: http://gateway-center:8992/api-s/security/v1/getCurrentUserAuth
      prefer-token-info: false
ribbon:
  ReadTimeout: 10000001
  ConnectTimeout: 10000001
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000001